language: erlang

env:
  - LUAROCKS_VERSION="2.1.2"

branches:
  only:
    - master

before_install:
  - sudo apt-get install lua luarocks
  - sudo luarocks install busted
  - sudo luarocks install fakeredis
  - sudo luarocks install luabitop
  - sudo luarocks install luacov
  - sudo luarocks install luacov-coveralls
  - sudo lua ./bin/dependencies

script:
  - ./bin/make-check

after_success:
  - luacov-coveralls --rot src/

notifications:
  recipients:
    - alban.linard@lsv.ens-cachan.fr
  email:
    on_success: change
    on_failure: always
