language: node_js

node_js:
  - 0.10

env:
  - LUA=""
  - LUA="luajit"

branches:
  only:
    - master

install:
  - sudo apt-get install lua5.2
  - sudo apt-get install luarocks
  - sudo luarocks install luassert
  - sudo luarocks install luacov
  - sudo luarocks install luacheck
  - sudo npm install -g docco

script: "./bin/make-all"

notifications:
  recipients:
    - alban.linard@lsv.ens-cachan.fr
  email:
    on_success: change
    on_failure: always
