language: node_js

node_js:
  - 0.10

env:
  - LUAROCKS_VERSION="2.1.2"

branches:
  only:
    - master

install:
  - sudo apt-get install npm
  - sudo npm install -g docco
  - sudo apt-get install lua5.2
  - sudo apt-get install lua5.2-dev
  - wget http://luarocks.org/releases/luarocks-${LUAROCKS_VERSION}.tar.gz
  - tar zxvpf luarocks-${LUAROCKS_VERSION}.tar.gz
  - cd luarocks-${LUAROCKS_VERSION}
  - ./configure --prefix=${HOME} --lua-version=5.2 --with-lua-include="/usr/include/lua5.2"
  - make bootstrap
  - cd ..
  - ${HOME}/bin/luarocks install luassert
  - ${HOME}/bin/luarocks install luacov
  - ${HOME}/bin/luarocks install luacheck

script: "./bin/make-all"

notifications:
  recipients:
    - alban.linard@lsv.ens-cachan.fr
  email:
    on_success: change
    on_failure: always
